### ISSUE TITLE
Support for Python <3.6

### ISSUE THREAD

**Issue by aliyilmazz** [wtsi-hgi/consul-lock#2]
hello, I can't install your library with provided instructions. Error message is as follows:

```
$ pip install git+https://github.com/wtsi-hgi/consul-lock.git@master#egg=consullock
Collecting consullock from git+https://github.com/wtsi-hgi/consul-lock.git@master#egg=consullock
  Cloning https://github.com/wtsi-hgi/consul-lock.git (to master) to /tmp/pip-build-vnsw93ha/consullock

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vnsw93ha/consullock/setup.py", line 24
        f"{EXECUTABLE_NAME}=consullock.cli:entrypoint"
                                                     ^
    SyntaxError: invalid syntax
```

Any help would be appreciated a lot.

**Comment by colin-nolan** [comment]
Hello. Are you using Python 3.6 or above?

**Comment by aliyilmazz** [comment]
hey, thanks for fast response. I'm using python 3.5.2.

well, I just realized that your repo requires python >=3.6. 

Just asking out of context, am I supposed to experience any compile errors for the code that I wrote in python 3.5.2? I'm planning to upgrade python to 3.6 and use consullock in my project but I'm concerned about any possible incompatibility issue.

**Comment by colin-nolan** [comment]
As it stands, the tool requires Python 3.6 or above (the f-string (https://www.python.org/dev/peps/pep-0498/) is not syntactically valid in 3.5, hence the problem you encountered).

It probably wouldn't be too difficult to support 3.5 but supporting old versions of Python is not on our roadmap.

**Comment by stefreak** [comment]
@colin-nolan would you accept a patch that adds python 3.5 support? Of course including travis ci tests for py3.5.

We are currently maintaining our own consul lock library and would switch to yours, but as we use a lot of Ubuntu 16.04 in our fleet and want to go to python3.6 with Ubuntu 18.04 we are have to support python3.5.

**Comment by colin-nolan** [comment]
@stefreak yes, I'd be happy to do that. I assume that it's only the f-strings that would have to go?
